version: "3.8"

services:
  remark42:
    image: ghcr.io/umputun/remark42:latest
    container_name: remark42
    restart: always
    # Load configuration (including secrets) from .env (gitignored)
    env_file:
      - .env
    # If you are NOT fronting with a reverse proxy, uncomment the port mapping
    # and access via http://<host>:8080 (but keep REMARK_URL set to your real HTTPS domain).
    # ports:
    #   - "8080:8080"

    # If using a proxy (e.g., Caddy/NGINX), connect both containers to the same
    # Docker network and proxy to http://remark42:8080
    # networks:
